#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Container image configuration
quarkus.container-image.build=true
quarkus.container-image.name=rimfrost-process-vah
quarkus.container-image.tag=latest
quarkus.container-image.group=rimfrost
quarkus.container-image.push=false

quarkus.index-dependency.rimfrost-framework-process.group-id=se.fk.rimfrost.framework.process
quarkus.index-dependency.rimfrost-framework-process.artifact-id=rimfrost-framework-process

# Packaging
# quarkus.package.jar.type=fast-jar

PROCESS_ID=vah

mp.messaging.incoming.vah-handlaggning-requests.connector=smallrye-kafka
mp.messaging.incoming.vah-handlaggning-requests.auto.offset.reset=earliest
mp.messaging.incoming.vah-handlaggning-requests.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.outgoing.handlaggning-responses.connector=smallrye-kafka
mp.messaging.outgoing.handlaggning-responses.value.serializer=org.apache.kafka.common.serialization.StringSerializer

kogito.quarkus.events.threads.queueSize=10
kogito.messaging.as-cloudevents=true

kogito.persistence.type=jdbc
kogito.persistence.proto.marshaller=false
kogito.persistence.query.timeout.millis=10000

kie.flyway.enabled=true

quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_URL}

%test.quarkus.kafka.devservices.topic-partitions.vah-handlaggning-requests=1
%test.quarkus.kafka.devservices.topic-partitions.handlaggning-responses=1
%test.quarkus.kafka.devservices.topic-partitions.rtf-maskinell-requests=1
%test.quarkus.kafka.devservices.topic-partitions.rtf-maskinell-responses=1
%test.quarkus.kafka.devservices.topic-partitions.rtf-manuell-requests=1
%test.quarkus.kafka.devservices.topic-partitions.rtf-manuell-responses=1
%test.quarkus.kafka.devservices.topic-partitions.rtf-manuell-komplettering-requests=1
%test.quarkus.kafka.devservices.topic-partitions.rtf-manuell-komplettering-responses=1
%test.quarkus.kafka.devservices.topic-partitions.bekraftabeslut-requests=1
%test.quarkus.kafka.devservices.topic-partitions.bekraftabeslut-responses=1
